# Generated by Django 4.1.2 on 2022-10-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('classe_Person', models.CharField(choices=[('GUER', 'Guerreiro'), ('MAGO', 'Mago'), ('ARQU', 'Arqueiro'), ('NECRO', 'Necromante')], default=0, max_length=5)),
                ('destino', models.CharField(choices=[('GLOR', 'Glória eterna'), ('VING', 'Vingança sem fim'), ('AMOR', 'Um belo amor')], default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
