# Generated by Django 4.1.2 on 2022-10-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0002_alter_personagem_classe_person_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personagem',
            new_name='Personagem1',
        ),
    ]
